apiVersion: v1
kind: Template
labels:
  template: source-secret
  credential.sync.jenkins.openshift.io: 'true'
metadata:
  name: source-secret
objects:
- apiVersion: v1
  stringData:
    password: ${PASSWORD}
    username: ${USERNAME}
  kind: Secret
  metadata:
    labels:
      credential.sync.jenkins.openshift.io: true
    name: ${SECRET_NAME}
    type: kubernetes.io/basic-auth
parameters:
- description: The password for the secret
  displayName: Secret password shhh
  name: PASSWORD
  generate: expression
  from: "[a-zA-Z0-9]{20}"
- description: The username for the secret
  displayName: Username for the secret
  name: USERNAME
  value: admin
- description: The name for the newly created secret
  displayName: Secret name
  name: SECRET_NAME